export const keywords = [
    "explore kohat",
    "kohat connect",
    "kohat connect app",
    "kohat connect website",
    "kohat connect platform",
    "apna kohat",
    "kohat app",
    "kohat website",
    "kohat platform",
    "kohat community",
    "Best marketplace in kohat",
    "Best marketplace in kohat city",
    "Best marketplace in kohat pakistan",
    "best marble supplier in kohat",
    "best furniture supplier in kohat",
    "best electronics supplier in kohat",
    "best clothing supplier in kohat",
    "best grocery supplier in kohat",
    "best restaurant in kohat",
    "best cafe in kohat",
    "best hotel in kohat",
    "best service provider in kohat",
    "nadra office in kohat",
    "passport office in kohat",
    "kohat connect app download",
    "kohat connect website download",
    "kohat connect platform download",
    "computer repair in kohat",
    "mobile repair in kohat",
    "car repair in kohat",
    "best car mechanic in kohat",
    "best mobile repair shop in kohat",
    "best computer repair shop in kohat",
    "best honda center in kohat",
    "best suzuki center in kohat",
    "best toyota center in kohat",
    "best school in kohat",
    "best college in kohat",
    "best university in kohat",
    "kohat school",
    "kohat college",
    "kohat university",
    "best hospital in kohat",
    "best clinic in kohat",
    "best doctor in kohat",
    "best dentist in kohat",
    "best pharmacy in kohat",
    "best gym in kohat",
    "best fitness center in kohat",
    "best yoga center in kohat",
    "best spa in kohat",
    "best salon in kohat",
    "gym in kohat",
    "fitness center in kohat",
    "yoga center in kohat",
    "spa in kohat",
    "salon in kohat",
    "banks in kohat",
    "atm in kohat",
    "best bank in kohat",
    "best atm in kohat",
    "meezan bank in kohat",
    "hbl bank in kohat",
    "allied bank in kohat",
    "askari bank in kohat",
    "faysal bank in kohat",
    "bank alfalah in kohat",
    "bank al habib in kohat",
    "bank islami in kohat",
    "bank of khyber in kohat",
    "bank of punjab in kohat",
    "bank of kpk in kohat",
    "how to reach kohat tanda dam in kohat",
    "how to reach kohat shenawa dam in kohat",
    "how to reach kohat khanpur dam in kohat",
    "software houses in kohat",
    "best software house in kohat",
    "best software development company in kohat",
    "best web development company in kohat",
    "best mobile app development company in kohat",
    "best software development company in kohat city",
    "best software development company in kohat pakistan",
    "best web development company in kohat city",
    "best mobile app development company in kohat city",
    "best software development company in kohat city pakistan",
    "best web development company in kohat city pakistan",
    "best mobile app development company in kohat city pakistan",
    "clothing stores in kohat",
    "best clothing store in kohat",
    "best clothing store in kohat city",
    "kohat bazaar",
    "kohat market",
    "kohat shopping",
    "mian bazaar in kohat",
    "kohat mall",
    "kohat shopping mall",
    "mian kheel bazaar in kohat",
    "kohat market near me",
    "kohat bazaar near me",
    "kohat shopping near me",
    "kohat mall near me",
    "kohat shopping mall near me",
    "kohat connect app ios",
    "kohat connect app android",
    "kohat connect customer care",
    "kohat connect support",
    "kohat connect review",
    "kohat connect rating",
    "kohat connect features",
    "kohat connect price",
    "kohat connect free download",
    "kohat jobs",
    "jobs in kohat",
    "kohat job portal",
    "kohat connect jobs",
    "employment in kohat",
    "part time jobs kohat",
    "full time jobs kohat",
    "kohat internship",
    "kohat freelancing",
    "kohat online work",
    "real estate in kohat",
    "property in kohat",
    "plots in kohat",
    "houses for sale in kohat",
    "houses for rent in kohat",
    "kohat land for sale",
    "kohat real estate agent",
    "best real estate agent in kohat",
    "kohat property dealer",
    "kohat construction company",
    "best construction company in kohat",
    "travel agency in kohat",
    "best travel agency in kohat",
    "kohat to islamabad transport",
    "kohat to peshawar transport",
    "kohat to rawalpindi transport",
    "kohat taxi service",
    "kohat rent a car",
    "kohat bus service",
    "daewoo kohat",
    "kohat railway station",
    "kohat airport",
    "flights from kohat",
    "kohat petrol pump",
    "best petrol pump in kohat",
    "cng station in kohat",
    "kohat car wash",
    "best car wash in kohat",
    "kohat tyre shop",
    "best tyre shop in kohat",
    "kohat oil change",
    "kohat car accessories",
    "kohat bike repair",
    "best bike mechanic in kohat",
    "honda bike center kohat",
    "yamaha bike center kohat",
    "suzuki bike center kohat",
    "uniform store in kohat",
    "school uniform in kohat",
    "sports shop in kohat",
    "best sports shop in kohat",
    "book shop in kohat",
    "stationery shop in kohat",
    "gift shop in kohat",
    "bakery in kohat",
    "best bakery in kohat",
    "sweet shop in kohat",
    "ice cream parlor in kohat",
    "fast food in kohat",
    "pizza in kohat",
    "burger in kohat",
    "bbq in kohat",
    "desi food in kohat",
    "chinese food in kohat",
    "continental food in kohat",
    "kohat food street",
    "kohat restaurant delivery",
    "tiffin service in kohat",
    "home chef in kohat",
    "catering in kohat",
    "best catering in kohat",
    "event planner in kohat",
    "best event planner in kohat",
    "wed hall in kohat",
    "marquee in kohat",
    "kohat photography",
    "best photographer in kohat",
    "videography in kohat",
    "bridal makeup in kohat",
    "best salon for women in kohat",
    "best salon for men in kohat",
    "barber in kohat",
    "best barber in kohat",
    "hair dresser in kohat",
    "facial in kohat",
    "nail salon in kohat",
    "waxing in kohat",
    "threading in kohat",
    "massage center in kohat",
    "best massage in kohat",
    "chiropractor in kohat",
    "physiotherapy in kohat",
    "best physiotherapist in kohat",
    "eye doctor in kohat",
    "best eye specialist in kohat",
    "children doctor in kohat",
    "skin doctor in kohat",
    "heart specialist in kohat",
    "neurologist in kohat",
    "orthopedic doctor in kohat",
    "gynecologist in kohat",
    "urologist in kohat",
    "ENT specialist in kohat",
    "psychologist in kohat",
    "psychiatrist in kohat",
    "lab test in kohat",
    "blood test in kohat",
    "x ray in kohat",
    "ultrasound in kohat",
    "MRI in kohat",
    "CT scan in kohat",
    "dental clinic in kohat",
    "teeth whitening in kohat",
    "root canal in kohat",
    "braces in kohat",
    "dental implant in kohat",
    "veterinary in kohat",
    "pet doctor in kohat",
    "pet shop in kohat",
    "pet grooming in kohat",
    "pet boarding in kohat",
    "lawyer in kohat",
    "best lawyer in kohat",
    "advocate in kohat",
    "court in kohat",
    "notary public in kohat",
    "accountant in kohat",
    "best accountant in kohat",
    "tax consultant in kohat",
    "auditor in kohat",
    "business consultant in kohat",
    "digital marketing agency in kohat",
    "best digital marketer in kohat",
    "seo expert in kohat",
    "social media manager in kohat",
    "graphic designer in kohat",
    "best graphic designer in kohat",
    "video editor in kohat",
    "content writer in kohat",
    "translator in kohat",
    "tutor in kohat",
    "home tutor in kohat",
    "academy in kohat",
    "computer academy in kohat",
    "english academy in kohat",
    "ielts in kohat",
    "pte in kohat",
    "toefl in kohat",
    "spoken english in kohat",
    "quran academy in kohat",
    "madrasa in kohat",
    "driving school in kohat",
    "best driving school in kohat",
    "vehicle registration in kohat",
    "excise office kohat",
    "police station in kohat",
    "fire brigade in kohat",
    "electrician in kohat",
    "plumber in kohat",
    "carpenter in kohat",
    "painter in kohat",
    "welder in kohat",
    "mechanic in kohat",
    "AC repair in kohat",
    "fridge repair in kohat",
    "washing machine repair in kohat",
    "microwave repair in kohat",
    "generator repair in kohat",
    "UPS repair in kohat",
    "solar panel in kohat",
    "best solar company in kohat",
    "water purifier in kohat",
    "bore well in kohat",
    "gardener in kohat",
    "cleaning service in kohat",
    "housekeeping in kohat",
    "maid service in kohat",
    "cook service in kohat",
    "driver service in kohat",
    "security guard in kohat",
    "cctv installation in kohat",
    "home alarm in kohat",
    "interior designer in kohat",
    "best interior designer in kohat",
    "furniture shop in kohat",
    "bed in kohat",
    "sofa in kohat",
    "dining table in kohat",
    "kitchen cabinet in kohat",
    "wardrobe in kohat",
    "carpet shop in kohat",
    "curtain shop in kohat",
    "paint shop in kohat",
    "hardware store in kohat",
    "sanitary shop in kohat",
    "tiles shop in kohat",
    "cement supplier in kohat",
    "steel supplier in kohat",
    "wood supplier in kohat",
    "marble shop in kohat",
    "granite shop in kohat",
    "building material in kohat",
    "kohat development authority",
    "kohat municipal committee",
    "wasa kohat",
    "pesco kohat",
    "sui gas kohat",
    "ptcl kohat",
    "nayatel kohat",
    "internet service in kohat",
    "broadband in kohat",
    "wifi in kohat",
    "cable tv in kohat",
    "kohat news",
    "kohat times",
    "kohat today",
    "kohat updates",
    "kohat weather",
    "kohat map",
    "kohat postal code",
    "kohat area code",
    "kohat distance from islamabad",
    "kohat distance from peshawar",
    "kohat to lahore distance",
    "kohat to karachi distance",
    "tourist places in kohat",
    "kohat fort",
    "kohat cantonment",
    "kohat bazar",
    "kohat gumbat",
    "kohat jawar",
    "kohat kotal",
    "kohat tunnel",
    "hangu road kohat",
    "darra adam khel kohat",
    "kachai kohat",
    "shakardara kohat",
    "lachi kohat",
    "jungle khel kohat",
    "billitang kohat",
    "Bahadur Kot kohat",
    "ghazikot kohat",
    "sultan khel kohat",
    "mula khel kohat",
    "khurram kohat",
    "kohat public library",
    "kohat sports complex",
    "kohat stadium",
    "kohat park",
    "kohat zoo",
    "kohat museum",
    "kohat golf club",
    "kohat race course",
    "kohat picnic point",
    "kohat dam view point",
    "camping in kohat",
    "hiking in kohat",
    "trekking near kohat",
    "fishing in kohat dam",
    "boating in kohat",
    "kohat night life",
    "kohat hotel booking",
    "kohat guest house",
    "best guest house in kohat",
    "kohat hostel",
    "boys hostel in kohat",
    "girls hostel in kohat",
    "paying guest in kohat",
    "marriage hall in kohat",
    "community center in kohat",
    "jamia mosque kohat",
    "eidgah kohat",
    "imambargah kohat",
    "church in kohat",
    "temple in kohat",
    "kohat cemetery",
    "charity in kohat",
    "ngo in kohat",
    "blood bank in kohat",
    "ambulance service in kohat",
    "rescue 1122 kohat",
    "civil defense kohat",
    "kohat women chamber",
    "kohat traders association",
    "darbar kohat",
    "horse riding in kohat",
    "swimming pool in kohat",
    "snooker club in kohat",
    "table tennis in kohat",
    "badminton court in kohat",
    "football ground in kohat",
    "cricket ground in kohat",
    "kohat cricket team",
    "kohat football club",
    "kohat marathon",
    "kohat half marathon",
    "auction in kohat",
    "second hand goods in kohat",
    "olx kohat",
    "facebook marketplace kohat",
    "kohat connect buy sell",
    "kohat online shopping",
    "kohat home delivery",
    "kohat ecommerce",
    "kohat startup",
    "kohat business idea",
    "kohat investment",
    "kohat franchise",
    "kohat shop for rent",
    "kohat office for rent",
    "kohat warehouse for rent",
    "kohat plot for sale",
    "kohat residential plot",
    "kohat commercial plot",
    "kohat agricultural land",
    "kohat factory for sale",
    "kohat godown for rent",
    "kohat hotel for sale",
    "kohat restaurant for sale",
    "kohat cafe for sale",
    "kohat salon for sale",
    "kohat pharmacy for sale",
    "kohat clinic for sale",
    "kohat school for sale",
    "kohat building for sale",
    "kohat floor for rent",
    "kohat room for rent",
    "kohat hostel for rent",
    "kohat hostel for boys",
    "kohat hostel for girls",
    "kohat hotel room price",
    "kohat food price",
    "kohat living cost",
    "kohat monthly expense",
    "kohat income level",
    "kohat per capita income",
    "kohat hdi",
    "kohat literacy rate",
    "kohat population",
    "kohat area sq km",
    "kohat city population",
    "kohat tehsil",
    "kohat district",
    "kohat division",
    "kohat mna",
    "kohat mpa",
    "kohat mayor",
    "kohat political map",
    "kohat election result",
    "kohat vote",
    "kohat citizen portal",
    "kohat complaint cell",
    "kohat digital city",
    "kohat smart city",
    "kohat connect business listing",
    "kohat connect verified",
    "kohat connect contact number",
    "kohat connect email",
    "kohat connect office address",
    "kohat connect head office",
    "kohat connect franchise",
    "kohat connect partner",
    "kohat connect merchant",
    "kohat connect vendor",
    "kohat connect offer",
    "kohat connect coupon",
    "kohat connect promo code",
    "kohat connect discount",
    "kohat connect deals",
    "kohat connect near me",
    "kohat connect top rated",
    "kohat connect best",
    "kohat connect trusted",
    "kohat connect reliable",
    "kohat connect safe",
    "kohat connect fast",
    "kohat connect easy",
    "kohat connect free",
    "kohat connect registration",
    "kohat connect sign up",
    "kohat connect login",
    "kohat connect dashboard",
    "kohat connect profile",
    "kohat connect settings",
    "kohat connect help",
    "kohat connect faq",
    "kohat connect tutorial",
    "kohat connect video",
    "kohat connect blog",
    "kohat connect guide",
    "kohat connect manual",
    "kohat connect update",
    "kohat connect new version",
    "kohat connect latest",
    "kohat connect beta",
    "kohat connect feedback",
    "kohat connect suggestion",
    "kohat connect complaint",
    "kohat connect refund",
    "kohat connect privacy policy",
    "kohat connect terms of service",
    "kohat connect security",
    "kohat connect data safety",
    "kohat tourism",
    "kohat travel guide",
    "kohat tourist attractions",
    "kohat hotels",
    "kohat restaurants",
    "kohat shopping",
    "kohat nightlife",
    "kohat events",
    "kohat culture",
    "kohat history",
    "kohat weather",
    "kohat map",
    "kohat transportation",
    "kohat local transport",
    "kohat car rental",
    "kohat taxi",
    "kohat airport",
    "kohat railway station",
    "kohat gallery",
    "kohat art gallery",
    "kohat music",
    "kohat dance",
    "kohat literature",
    "kohat poetry",
    "kohat festivals",
    "kohat holidays",
    "kohat vacations",
    "kohat weekend getaways",
    "kohat day trips",
    "kohat bike showrooms",
    "kohat car showrooms",
    "kohat auto showrooms",
    
];